### ISSUE TITLE
Login w/ HTTPS

### ISSUE THREAD

**Issue by unsafecode** [cofoundry-cms/cofoundry#195] opened 2018-04-05 15:12 UTC
We're experiencing issues when accessing the admin dashboard behind a SSL-termining proxy.

In this case, the login form appears, but after a successful login we get a redirection to the http: scheme (which is not exposed). However, even when rewriting to the correct scheme, authentication looks like not to work, and the login form appears again.

On the other hand, navigating the very same site downstream the SSL-terminating proxy (without HTTPS) yields the expected behavior, and dashboard opens. The same applies when using a local proxy w/ self-signed SSL certificate.

**Comment by HeyJoel** [comment] 2018-04-05 15:50
I think this will be an issue caused by your proxy switching the request between http/https which causes a problem with the auth cookie. What I think you're seeing is the auth cookie not being set and therefore being redirected back to login.

I seem to remember having a similar issue when setting up SSL through CloudFlare, and my solution was to install a certificate on my server to ensure traffic was https all the way. Presumably this isn't an option for you?

**Comment by unsafecode** [comment] 2018-04-05 22:03
Unfortunately, it is not. Is there a way to ensure the authorities cookie works across schemes?

**Comment by HeyJoel** [comment] 2018-04-06 09:11
It might take me a while for me to set up and replicate the issue, but perhaps I can direct you to a possible solution.

It's possible this isn't a Cofoundry specific issue, but rather something you could fix early on in middleware. [This Identity Sever issue](https://github.com/IdentityServer/IdentityServer4/issues/324) seems to be similar to what you're describing and lists some solutions to change the scheme in HttpContext. [This issue](https://github.com/aspnet/Antiforgery/issues/159) is also similar but talks more specifically about secure cookies, again the solution is using UseForwardedHeaders middleware to modify the request.

Our auth cookie settings use the default [`CookieSecurePolicy.SameAsRequest`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.cookiesecurepolicy?view=aspnetcore-2.0) value which should work fine if the request we receive is the same scheme as the expected response to the client. If need be I can look at providing a way for you to easily modify those cookie settings.

**Comment by unsafecode** [comment] 2018-04-06 15:13
Tried out with UseForwardedHeaders, even clearing the KnowNetworks settings like someone suggested - but issue is still present.

Either way, it looks like to be an issue with the Auth Cookie, as you mentioned. I'll keep investigating.

**Comment by HeyJoel** [comment] 2018-05-01 13:52
Did you managed to resolve this issue @unsafecode?

**Comment by unsafecode** [comment] 2018-05-03 07:33
@HeyJoel Not quite. We event tried to use an additional dedicated load balancer: the login is then successful, but after navigating to an item detail, the user gets logged out.

I'm also trying to add IgnoreAntiforgeryToken as a global filter (this would be an Intranet portal), but still does not look like to yield any effect...

**Comment by HeyJoel** [comment] 2018-05-04 14:36
@unsafecode I mentioned earlier that I could make it easier for you to alter our cookie settings. I don't think these settings are causing your issue but this might help eliminate that from your investigations. I've just pushed changes that will allow you to do this. You can find the updates in our [MyGet feed](https://www.myget.org/gallery/cofoundry) in the 0.3.2-beta0010 pre-release packages.

**Disclaimer: that this area will likely change in an upcoming release which may cause breaking changes**

The following example shows you how to override our default auth cookie configuration so you can modify it as you please:

```csharp
using Cofoundry.Core.DependencyInjection;
using Cofoundry.Domain;
using Cofoundry.Web;
using Microsoft.Extensions.DependencyInjection;
using System.Linq;

/// <summary>
/// Use an IDependencyRegistration instance to override the default implementation
/// </summary>
public class AuthDependencyRegistration : IDependencyRegistration
{
    public void Register(IContainerRegister container)
    {
        container.Register<IAuthConfiguration, CustomAuthConfiguration>(RegistrationOptions.Override());
    }
}
    
/// <summary>
/// This is a copy of the default config
/// </summary>
public class CustomAuthConfiguration : IAuthConfiguration
{
    private readonly IUserAreaDefinitionRepository _userAreaDefinitionRepository;
    private readonly IAuthCookieNamespaceProvider _authCookieNamespaceProvider;

    public CustomAuthConfiguration(
        IUserAreaDefinitionRepository userAreaDefinitionRepository,
        IAuthCookieNamespaceProvider authCookieNamespaceProvider
        )
    {
        _userAreaDefinitionRepository = userAreaDefinitionRepository;
        _authCookieNamespaceProvider = authCookieNamespaceProvider;
    }

    public void Configure(IMvcBuilder mvcBuilder)
    {
        var services = mvcBuilder.Services;
        var allUserAreas = _userAreaDefinitionRepository.GetAll();

        // Set default schema as specified in config, falling back to CofoundryAdminUserArea
        // Since any additional areas are configured by the implementor there shouldn't be multiple
        // unless the developer has misconfigured their areas.
        var defaultSchemaCode = allUserAreas
            .OrderByDescending(u => u.IsDefaultAuthSchema)
            .ThenByDescending(u => u is CofoundryAdminUserArea)
            .ThenBy(u => u.Name)
            .Select(u => u.UserAreaCode)
            .First();

        var defaultScheme = CofoundryAuthenticationConstants.FormatAuthenticationScheme(defaultSchemaCode);

        var authBuilder = mvcBuilder.Services.AddAuthentication(defaultScheme);
        var cookieNamespace = _authCookieNamespaceProvider.GetNamespace();

        foreach (var userAreaDefinition in allUserAreas)
        {
            var scheme = CofoundryAuthenticationConstants.FormatAuthenticationScheme(userAreaDefinition.UserAreaCode);

            // You may wish to amend the cookie setting here.
            authBuilder
                .AddCookie(scheme, cookieOptions =>
                {
                    cookieOptions.Cookie.Name = cookieNamespace + userAreaDefinition.UserAreaCode;
                    cookieOptions.Cookie.HttpOnly = true;

                    if (!string.IsNullOrWhiteSpace(userAreaDefinition.LoginPath))
                    {
                        cookieOptions.LoginPath = userAreaDefinition.LoginPath;
                    }
                });
        }
    }
}
```

**Comment by HeyJoel** [comment] 2018-08-29 13:28
I'm closing this as there's no further activity and I belive this to be an issue with the deployment environment or non-Cofoundry application configuration.

Do let me know if you think this is still an issue with Cofoundry rather than the environemnt or application setup.

**Closed by HeyJoel** 2018-08-29 13:28 UTC
