### ISSUE TITLE
Question about "FilteredSelectList"

### ISSUE THREAD

**Issue by TiriTM** [cofoundry-cms/cofoundry#328] opened 2019-07-08 15:26 UTC
Hi there,

is there any way to get a filterable dropdown list (filled by an API) in the admin panel?

**Background:** 
I'm currently trying to implement a CustomEntity with a list of products comin' from an API. Therefore I've created a class ProductOptionSource that inherits from IListOptionApiSource (thanks again for this hint @HeyJoel) and use this as type for the dropdown in my ProductDataModel class.
```
public class ProductOptionSource : IListOptionApiSource
{
	public string Path => "/admin/api/content/products";
	public string NameField => "distinctiveTitle";
	public string ValueField => "productReference";
}

public class ProductDataModel : ICustomEntityDataModel
{
	[Display(Description = "Select a product.")]
	[SelectList(typeof(ProductOptionSource))]
	public ProductOptionSource Product {get; set;}
}
```

Because this list might easily contain tenthousands of options, I need a possibility to dynamically filter it. Therefore I searched the documentation, google and stackoverflow for some information how to do so and found ... nothin' helpful. Some references in github issues to something like "FilteredSelectList" and a "FormFieldFilteredDropdown" but there's nothin' like this found if I try `[FilteredSelectList(typeof(ProductOptionSource))]` for the product dropdown so I only get "The type or namespace 'FilteredSelectList' was not found ...".

Any help is very appreciated.
Thanks in advance and kind regards.

**Comment by HeyJoel** [comment] 2019-07-08 22:00
The `FilteredSelectListAttribute` has not been implemented yet, duplicate of #236.

**Closed by HeyJoel** 2019-07-08 22:00 UTC
Labels: duplicate
