### ISSUE TITLE
Add Custom Menu For Social Media.

### ISSUE THREAD

**Issue by sunny7713** [cofoundry-cms/cofoundry#430] opened 2021-04-21 08:03 UTC
I Have One Question  I want to Add Social media link in footer .How to possible it. Please let me know.

**Comment by HeyJoel** [comment] 2021-04-28 10:45
If you're referring to making the footer content manageable, then this is a duplicate of #358 or otherwise, you can just hardcode a link to the footer as you would do in regular ASP.NET

**Closed by HeyJoel** 2021-04-28 10:45 UTC
