### ISSUE TITLE
Social Media on Footer .

### ISSUE THREAD

**Issue by sunny7713** [cofoundry-cms/cofoundry#432] opened 2021-04-29 07:47 UTC
Please add social media links to the footer on all pages.
We have Facebook, Instagram LinkedIn.

This should be maintained via a menu. It's Possible or not 

for e.g Manage All Links by Admin Side (With Menu)

**Comment by HeyJoel** [comment] 2021-04-29 08:19
Duplicate of #358 or #243 - please read these issues.

**Closed by HeyJoel** 2021-04-29 08:19 UTC
