### ISSUE TITLE
Removing PageBlockType from source causes error

### ISSUE THREAD

**Issue by endrehegyi** [cofoundry-cms/cofoundry#357] opened 2019-12-08 19:29 UTC
I created all my PageBlockTypes as follows:
PageBlockTypes/CTA1/model + cshtml file 

If I remove this CTA1 folder from the PageBlockTypes I now get an error when starting up the application: 

> `An unhandled exception occurred while processing the request.
> FileNotFoundException: Page block type view file 'CTA1' not found.
> Cofoundry.Domain.GetPageBlockTypeFileDetailsByFileNameQueryHandler.ExecuteAsync(GetPageBlockTypeFileDetailsByFileNameQuery query, IExecutionContext executionContext) in GetPageBlockTypeFileDetailsByFileNameQueryHandler.cs, line 61
> 
> AutoUpdateFailedException: Error updating the system: Page block type view file 'CTA1' not found.
> Cofoundry.Web.AutoUpdateMiddleware.WaitForCompletionAsync(HttpContext cx, AutoUpdateState autoUpdateState) in AutoUpdateMiddleware.cs, line 102`

Re-Creating the folder and the file fixes the problem but I imagined that the system would auto-update and realise that the folder has been removed and that it should no longer look for it.

**Comment by HeyJoel** [comment] 2019-12-08 20:17
That's strange, did you remove the block type data model (`IPageBlockTypeDataModel` implementation)? If that's removed it should be deleted by the `RegisterPageBlockTypesCommandHandler` at startup.

If that's not it, can you give the full stack trace? I expect it's during the execution of `RegisterPageBlockTypesCommandHandler`.

**Comment by endrehegyi** [comment] 2019-12-08 21:04
Yes I removed the Folder completely ( Both model and cshtml file) 
```
System.IO.FileNotFoundException: Page block type view file 'TitleMultiMD' not found.
   at Cofoundry.Domain.GetPageBlockTypeFileDetailsByFileNameQueryHandler.ExecuteAsync(GetPageBlockTypeFileDetailsByFileNameQuery query, IExecutionContext executionContext) in C:\projects\cofoundry\src\Cofoundry.Domain\Domain\PageBlockTypes\Queries\GetPageBlockTypeFileDetailsByFileNameQueryHandler.cs:line 61
   at Cofoundry.Domain.CQS.QueryExecutor.ExecuteQueryAsync[TQuery,TResult](TQuery query, IExecutionContext executionContext) in C:\projects\cofoundry\src\Cofoundry.Domain\CQS\Framework\Query\QueryExecutor.cs:line 97
   at Cofoundry.Domain.CQS.QueryExecutor.ExecuteAsync[TResult](IQuery`1 query, IExecutionContext executionContext)
   at Cofoundry.Domain.RegisterPageBlockTypesCommandHandler.UpdateBlocksAsync(IExecutionContext executionContext, Dictionary`2 dbPageBlockTypes, Dictionary`2 blockTypeDataModels) in C:\projects\cofoundry\src\Cofoundry.Domain\Domain\PageBlockTypes\Commands\RegisterPageBlockTypesCommandHandler.cs:line 83
   at Cofoundry.Domain.RegisterPageBlockTypesCommandHandler.ExecuteAsync(RegisterPageBlockTypesCommand command, IExecutionContext executionContext) in C:\projects\cofoundry\src\Cofoundry.Domain\Domain\PageBlockTypes\Commands\RegisterPageBlockTypesCommandHandler.cs:line 65
   at Cofoundry.Domain.CQS.CommandExecutor.ExecuteCommandAsync[TCommand](TCommand command, IExecutionContext executionContext) in C:\projects\cofoundry\src\Cofoundry.Domain\CQS\Framework\Command\CommandExecutor.cs:line 141
   at Cofoundry.Domain.CQS.CommandExecutor.ExecuteCommandAsync[TCommand](TCommand command, IExecutionContext executionContext) in C:\projects\cofoundry\src\Cofoundry.Domain\CQS\Framework\Command\CommandExecutor.cs:line 146
   at Cofoundry.Domain.CQS.CommandExecutor.ExecuteAsync(ICommand command, IExecutionContext executionContext) in C:\projects\cofoundry\src\Cofoundry.Domain\CQS\Framework\Command\CommandExecutor.cs:line 118
   at Cofoundry.Domain.Installation.RegisterPageTemplatesAndPageBlockTypesCommandHandler.ExecuteAsync(RegisterPageTemplatesAndPageBlockTypesCommand command) in C:\projects\cofoundry\src\Cofoundry.Domain\Install\AlwaysUpdateCommands\RegisterPageTemplatesAndPageBlockTypesCommandHandler.cs:line 30
   at Cofoundry.Core.AutoUpdate.AutoUpdateService.ExecutePackage(UpdatePackage package) in C:\projects\cofoundry\src\Cofoundry.Core\AutoUpdate\Services\AutoUpdateService.cs:line 125
   at Cofoundry.Core.AutoUpdate.AutoUpdateService.UpdateAsync() in C:\projects\cofoundry\src\Cofoundry.Core\AutoUpdate\Services\AutoUpdateService.cs:line 95
   at Cofoundry.Core.AutoUpdate.AutoUpdateService.UpdateAsync() in C:\projects\cofoundry\src\Cofoundry.Core\AutoUpdate\Services\AutoUpdateService.cs:line 102
   at Cofoundry.Web.AutoUpdateHostedService.TryUpdate() in C:\projects\cofoundry\src\Cofoundry.Web\App_Start\AutoUpdate\AutoUpdateHostedService.cs:line 88
```

&& Also : 

```
Cofoundry.Web.AutoUpdateFailedException: Error updating the system: Page block type view file 'TitleMultiMD' not found. ---> System.IO.FileNotFoundException: Page block type view file 'TitleMultiMD' not found.
   at Cofoundry.Domain.GetPageBlockTypeFileDetailsByFileNameQueryHandler.ExecuteAsync(GetPageBlockTypeFileDetailsByFileNameQuery query, IExecutionContext executionContext) in C:\projects\cofoundry\src\Cofoundry.Domain\Domain\PageBlockTypes\Queries\GetPageBlockTypeFileDetailsByFileNameQueryHandler.cs:line 61
   at Cofoundry.Domain.CQS.QueryExecutor.ExecuteQueryAsync[TQuery,TResult](TQuery query, IExecutionContext executionContext) in C:\projects\cofoundry\src\Cofoundry.Domain\CQS\Framework\Query\QueryExecutor.cs:line 97
   at Cofoundry.Domain.CQS.QueryExecutor.ExecuteAsync[TResult](IQuery`1 query, IExecutionContext executionContext)
   at Cofoundry.Domain.RegisterPageBlockTypesCommandHandler.UpdateBlocksAsync(IExecutionContext executionContext, Dictionary`2 dbPageBlockTypes, Dictionary`2 blockTypeDataModels) in C:\projects\cofoundry\src\Cofoundry.Domain\Domain\PageBlockTypes\Commands\RegisterPageBlockTypesCommandHandler.cs:line 83
   at Cofoundry.Domain.RegisterPageBlockTypesCommandHandler.ExecuteAsync(RegisterPageBlockTypesCommand command, IExecutionContext executionContext) in C:\projects\cofoundry\src\Cofoundry.Domain\Domain\PageBlockTypes\Commands\RegisterPageBlockTypesCommandHandler.cs:line 65
   at Cofoundry.Domain.CQS.CommandExecutor.ExecuteCommandAsync[TCommand](TCommand command, IExecutionContext executionContext) in C:\projects\cofoundry\src\Cofoundry.Domain\CQS\Framework\Command\CommandExecutor.cs:line 141
   at Cofoundry.Domain.CQS.CommandExecutor.ExecuteCommandAsync[TCommand](TCommand command, IExecutionContext executionContext) in C:\projects\cofoundry\src\Cofoundry.Domain\CQS\Framework\Command\CommandExecutor.cs:line 146
   at Cofoundry.Domain.CQS.CommandExecutor.ExecuteAsync(ICommand command, IExecutionContext executionContext) in C:\projects\cofoundry\src\Cofoundry.Domain\CQS\Framework\Command\CommandExecutor.cs:line 118
   at Cofoundry.Domain.Installation.RegisterPageTemplatesAndPageBlockTypesCommandHandler.ExecuteAsync(RegisterPageTemplatesAndPageBlockTypesCommand command) in C:\projects\cofoundry\src\Cofoundry.Domain\Install\AlwaysUpdateCommands\RegisterPageTemplatesAndPageBlockTypesCommandHandler.cs:line 30
   at Cofoundry.Core.AutoUpdate.AutoUpdateService.ExecutePackage(UpdatePackage package) in C:\projects\cofoundry\src\Cofoundry.Core\AutoUpdate\Services\AutoUpdateService.cs:line 125
   at Cofoundry.Core.AutoUpdate.AutoUpdateService.UpdateAsync() in C:\projects\cofoundry\src\Cofoundry.Core\AutoUpdate\Services\AutoUpdateService.cs:line 95
   at Cofoundry.Core.AutoUpdate.AutoUpdateService.UpdateAsync() in C:\projects\cofoundry\src\Cofoundry.Core\AutoUpdate\Services\AutoUpdateService.cs:line 102
   at Cofoundry.Web.AutoUpdateHostedService.TryUpdate() in C:\projects\cofoundry\src\Cofoundry.Web\App_Start\AutoUpdate\AutoUpdateHostedService.cs:line 88
   --- End of inner exception stack trace ---
   at Cofoundry.Web.AutoUpdateMiddleware.Invoke(HttpContext cx) in C:\projects\cofoundry\src\Cofoundry.Web\App_Start\AutoUpdate\AutoUpdateMiddleware.cs:line 51
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Cofoundry.Plugins.ErrorLogging.ErrorLoggingMiddleware.Invoke(HttpContext context, ILogger`1 logger, IErrorLoggingService errorLoggingService)
   at Cofoundry.Plugins.ErrorLogging.ErrorLoggingMiddleware.Invoke(HttpContext context, ILogger`1 logger, IErrorLoggingService errorLoggingService)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

I thought that maybe It's the database, so I created a brand new database connected it up and I get the same error.

**Comment by HeyJoel** [comment] 2019-12-09 10:42
So I've been able to reproduce this only through a set of specific actions:

- Delete the block type container folder e.g. *PageBlockTypes/CTA1/*
- Run the site with no other code changes

Forcing a rebuild or modifying a cs file seems to resolve the issue in my case. Also if I delete the files in the folder first before deleting the containing folder, then the issue does not occur.

I'm not sure why deleting the folder does not trigger .NET to recompile the site code, but the issue is because the deleted `IPageBlockTypeDataModel` is still in the assembly when we scan it at startup. The code that throws an error can only execute if the deleted page block type data model type is registered with the DI container.

This seems like a .NET bug, but we could provide more information with a custom error message in this case - there is also the possibility of a developer deleting the template file but not the dtaa model file so it would be useful in that case.

**Comment by endrehegyi** [comment] 2019-12-09 13:26
For me nothing seems to work apart from putting the files back. As soon as I remove them I get the error again. 
I've tried adding extra BlockTypes, changing CSS and forcing a rebuild with dotnet build but no luck : /

**Comment by HeyJoel** [comment] 2019-12-09 17:54
It looks to me like the cause of the error is that in `RegisterPageBlockTypesCommandHandler` the injected `IEnumerable<IPageBlockTypeDataModel> allPageBlockTypeDataModels` contains an `IPageBlockTypeDataModel` that does not have a view file associated with it. 

I don't know how the data model is getting injected into the class if you have deleted it and rebuilt, but you can try this debug code to get more information about the model type and parent assembly that's causing the issue. It will throw an exception at startup with more information about the missing file:

```csharp
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Cofoundry.Domain.CQS;
using Cofoundry.Domain;
using System.IO;
using Cofoundry.Core.DependencyInjection;
using System;

namespace Cofoundry.Debug
{
    public class DebugDependencyRegistration : IDependencyRegistration
    {
        public void Register(IContainerRegister container)
        {
            // Override the default handler registration
            container.Register<IAsyncCommandHandler<RegisterPageBlockTypesCommand>, DebugRegisterPageBlockTypesCommandHandler>(RegistrationOptions.Override());
        }
    }

    public class DebugRegisterPageBlockTypesCommandHandler
        : IAsyncCommandHandler<RegisterPageBlockTypesCommand>
        , IIgnorePermissionCheckHandler
    {
        private readonly IEnumerable<IPageBlockTypeDataModel> _allPageBlockTypeDataModels;
        private readonly IPageBlockTypeFileNameFormatter _blockTypeFileNameFormatter;
        private readonly IPageBlockTypeViewFileLocator _viewLocator;

        public DebugRegisterPageBlockTypesCommandHandler(
            IEnumerable<IPageBlockTypeDataModel> allPageBlockTypeDataModels,
            IPageBlockTypeFileNameFormatter blockTypeFileNameFormatter,
            IPageBlockTypeViewFileLocator viewLocator
            )
        {
            _viewLocator = viewLocator;
            _allPageBlockTypeDataModels = allPageBlockTypeDataModels;
            _blockTypeFileNameFormatter = blockTypeFileNameFormatter;
        }

        public Task ExecuteAsync(RegisterPageBlockTypesCommand command, IExecutionContext executionContext)
        {
            var blockTypeDataModels = _allPageBlockTypeDataModels.ToDictionary(m => FormatBlockTypeFileName(m));

            foreach (var model in blockTypeDataModels)
            {
                var fileName = model.Key;
                var viewPath = _viewLocator.GetPathByFileName(fileName);

                if (string.IsNullOrEmpty(viewPath))
                {
                    // throw a custom exception for the file that cannot be found
                    var dataModelType = model.Value.GetType();
                    var dataModelAssembly = dataModelType.Assembly;

                    var msg = $"View file '{fileName}' not found for model {dataModelType.FullName} in assembly {dataModelAssembly.FullName} in {dataModelAssembly.Location}";

                    throw new FileNotFoundException(msg);
                }

            }

            throw new Exception("No missing files - try removing the debug handler and trying again");
        }

        private string FormatBlockTypeFileName(IPageBlockTypeDataModel m)
        {
            return _blockTypeFileNameFormatter.FormatFromDataModelType(m.GetType());
        }
    }
}
```

Are you using .NET Core 2.2 and v0.6.1 of Cofoundry? What platform? Is this in the dev environment?

**Comment by endrehegyi** [comment] 2019-12-11 02:48
I'm using .net core 2.2 and v0.6.1 of Cofoundry yes. 

I've now tried manually removing the bin/obj folders  and then doing a full rebuild. This solves the problem. If I remove  another PageBlock the same issue happens again.

I'll just have to remove the bin/obj folders from now on if I remove a PageBlock.

**Comment by HeyJoel** [comment] 2020-02-18 15:47
I've added some additional information to the exception that is thrown when this occurs. I'll look into this again once the 3.1 upgrade has been completed to see if the framework behavior has changed.

**Comment by adamket** [comment] 2020-07-29 21:50
Chiming in: I experienced the same issue upon modifying the namespace of block types.  I have not been able to fix this issue by rebuilding or clearing the bin/obj directories, just by removing the blocks altogether.

**Comment by HeyJoel** [comment] 2020-07-30 08:18
Thanks @adamket , that's a new angle for me to investigate.

**Comment by HeyJoel** [comment] 2021-01-18 20:44
1. I can't seem to replicate the original issue anymore, I'm hoping it was fixed in a .NET core framework or VS update
2. Changing a block namespace won't affect the block, block names need to be unique irrespective of namespace or file placement.
3. Block files need to be located where Cofoundry can find them, three locations are included by default or you can register other locations, find more info in the [block type docs](https://www.cofoundry.org/docs/content-management/page-block-types#file-location)

I'm closing this now, if you have a related issue please open a new issue with details on how to reproduce the error.

**Closed by HeyJoel** 2021-01-18 20:44 UTC
Labels: bug
