### ISSUE TITLE
Can't complete setup

### ISSUE THREAD

**Issue by ctolkien** [cofoundry-cms/cofoundry#79] opened 2017-03-07 05:45 UTC
When trying to complete the /admin/setup step, there is an error raised (via JS):

>The anti-forgery token could not be decrypted. If this application is hosted by a Web Farm or cluster, ensure that all machines are running the same version of ASP.NET Web Pages and that the <machineKey> configuration specifies explicit encryption and validation keys. AutoGenerate cannot be used in a cluster."

I've configured the machine key as instructed in the setup guide. I can also see `X-XSRF-Token:` is being passed along in the headers .

**Comment by HeyJoel** [comment] 2017-03-07 12:05
I've had an issue like this before which was caused by an additional value being added to the `X-XSRF-Token` header. I resolved it by  disabling some of my chrome extensions but having done that I couldn't replicate the error again by turning them back on so I'm not sure if that was actually the cause or just a red-herring. 

Anyway, we use the [.Net AntiForgery library](https://github.com/cofoundry-cms/cofoundry/blob/master/src/Cofoundry.Web/Framework/AntiCSRF/AntiCSRFService.cs) to create and validate the tokens but for WebApi endpoints we have to do a bit of custom formatting of the token. Your token should look a bit like this:

`otYgl7rDQk5MBnoOfhO4PrYqKpKM4tN-NNNT8wt9a5uuu5DuQzL6jzOsomKjktbJZGp1AFc958-appof3p2FjxmMfdE1:ah5zQ3EpgR_RaQHZtqQWE7dSpj2v1ORNsFsW_xlavbTeubSTgfvA_1tgQxhTyvBR2WFckCIlyMbYA4rkKc0GhPHjdhE1` 

Note the colon delimiter between the two parts of the token. When I ran into the issue the header had an extra value added to the end separated by a comma. Is that what you are seeing?

I can't actually replicate the issue, but I've fixed it base on the assumption of a comma delimiter. You can get the fix in [version 0.1.2-ci0004](http://myget.org/feed/cofoundry/package/nuget/Cofoundry.Web.Admin) in our [pre-release myget feed](http://myget.org/gallery/cofoundry) or if you want to wait I'm hoping to get proper release in before the end of the week to fix this and a few other bugs.

**Comment by HeyJoel** [comment] 2017-03-27 10:24
This change has been released in 0.1.3. I'm closing for now, but if anyone has further problems let me know and i'll re-open.

**Closed by HeyJoel** 2017-03-27 10:24 UTC
Labels: bug
