### ISSUE TITLE
How to bulkupload image in cofoundry?

### ISSUE THREAD

**Issue by ramkrish3020** [cofoundry-cms/cofoundry#345] opened 2019-09-12 09:35 UTC
Hi,
  I trying to upload  one click multiple images, @HeyJoel Can you please help me on this any possible way is there.

**Comment by ramkrish3020** [comment] 2019-09-13 06:57
@HeyJoel Can you please help me on this.

**Comment by HeyJoel** [comment] 2019-09-15 10:48
This is a duplicate of #7. Please don't @ me telling me to hurry up on on issues, I don't always have time to respond. The project is open source and if you're in a hurry there's plenty of opportunity for you to dig in yourself and find out if the feature is supported.

**Closed by HeyJoel** 2019-09-15 10:48 UTC
Labels: duplicate
